Updated specification.

diff --git a/Tests/Mock Projects/After/AllTasks/.github/workflows/Workspace Validation.yaml b/Tests/Mock Projects/After/AllTasks/.github/workflows/Workspace Validation.yaml
--- a/Tests/Mock Projects/After/AllTasks/.github/workflows/Workspace Validation.yaml
+++ b/Tests/Mock Projects/After/AllTasks/.github/workflows/Workspace Validation.yaml
@@ -25,6 +25,70 @@ jobs:
         xcversion select 11.3
         './Refresh (macOS).command' •language '🇮🇱עב'
         './Validate (macOS).command' •job macos •language '🇮🇱עב'
+  Windows:
+    runs-on: windows-latest
+    steps:
+    - uses: actions/checkout@v1
+    - uses: actions/cache@v1
+      with:
+        key: Windows‐${{ hashFiles('Refresh*') }}‐${{ hashFiles('.github/workflows/**') }}
+        path: .build/SDG/Workspace
+    - name: Validate
+      shell: bash
+      run: |
+        echo 'Setting up Visual Studio... (in order to proceed as though in the Native Tools Command Prompt)'
+        repository_directory=$(pwd)
+        cd '/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build'
+        echo 'export -p > exported_environment.sh' > nested_bash.sh
+        echo 'vcvarsall.bat x64 && "C:/Program Files/Git/usr/bin/bash" -c ./nested_bash.sh' > export_environment.bat
+        cmd "/c export_environment.bat"
+        source ./exported_environment.sh
+        if [ -z "$INCLUDE" ]; then echo 'Failed to set up Visual Studio.'; exit 1; fi
+        cd "${repository_directory}"
+
+        echo 'Fetching Windows platform module maps...'
+        curl -L 'https://raw.githubusercontent.com/apple/swift/swift-5.2-branch/stdlib/public/Platform/ucrt.modulemap' -o "${UniversalCRTSdkDir}/Include/${UCRTVersion}/ucrt/module.modulemap"
+        curl -L 'https://raw.githubusercontent.com/apple/swift/swift-5.2-branch/stdlib/public/Platform/visualc.modulemap' -o "${VCToolsInstallDir}/include/module.modulemap"
+        curl -L 'https://raw.githubusercontent.com/apple/swift/swift-5.2-branch/stdlib/public/Platform/visualc.apinotes' -o "${VCToolsInstallDir}/include/visualc.apinotes"
+        curl -L 'https://raw.githubusercontent.com/apple/swift/swift-5.2-branch/stdlib/public/Platform/winsdk.modulemap' -o "${UniversalCRTSdkDir}/Include/${UCRTVersion}/um/module.modulemap"
+
+        echo 'Fetching Swift...'
+        mkdir -p .build/SDG/Experimental_Swift
+        cd .build/SDG/Experimental_Swift
+        curl -o swift-build.py 'https://raw.githubusercontent.com/compnerd/swift-build/master/utilities/swift-build.py'
+        python -m pip install --user azure-devops tabulate
+        echo 'Downloading... (This could take up to 10 minutes.)'
+        python swift-build.py --build-id 'VS2019 Swift 5.2' --latest-artifacts --filter windows-x64 --download > /dev/null
+        7z x toolchain-windows-x64.zip
+        mv toolchain-windows-x64/Library /c/Library
+        7z x sdk-windows-x64.zip
+        mv sdk-windows-x64/Library/Developer/Platforms /c/Library/Developer/Platforms
+        cd "${repository_directory}"
+        export PATH="/c/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/bin:${PATH}"
+        mkdir -p /c/Library/Swift/Current
+        cp -R /c/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk/usr/bin /c/Library/Swift/Current/bin
+        cp -R /c/Library/Developer/Platforms/Windows.platform/Developer/Library/XCTest-development/usr/bin/* /c/Library/Swift/Current/bin
+        export PATH="/c/Library/Swift/Current/bin:${PATH}"
+        swift --version
+
+        echo 'Fetching ICU...'
+        mkdir -p .build/SDG/ICU
+        cd .build/SDG/ICU
+        curl -L http://download.icu-project.org/files/icu4c/64.2/icu4c-64_2-Win64-MSVC2017.zip --output ICU.zip
+        7z x ICU.zip -oICU-64.2
+        mv ICU-64.2 /c/Library/ICU-64.2
+        mv /c/Library/ICU-64.2/bin64 /c/Library/ICU-64.2/bin
+        export PATH="/c/Library/ICU-64.2/bin:${PATH}"
+        cd "${repository_directory}"
+
+        echo 'Fetching package graph...'
+
+        echo 'Building AllTasks...'
+        cmake -G Ninja -S .github/workflows/Windows -B .build/SDG/CMake -DCMAKE_Swift_FLAGS='-resource-dir C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk\usr\lib\swift -L C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk\usr\lib\swift\windows -I C:\Library\Developer\Platforms\Windows.platform\Developer\Library\XCTest-development\usr\lib\swift\windows\x86_64 -L C:\Library\Developer\Platforms\Windows.platform\Developer\Library\XCTest-development\usr\lib\swift\windows' -DCMAKE_Swift_LINK_FLAGS='-resource-dir C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk\usr\lib\swift -L C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk\usr\lib\swift\windows -I C:\Library\Developer\Platforms\Windows.platform\Developer\Library\XCTest-development\usr\lib\swift\windows\x86_64 -L C:\Library\Developer\Platforms\Windows.platform\Developer\Library\XCTest-development\usr\lib\swift\windows'
+        cmake --build '.build/SDG/CMake'
+        echo 'Testing AllTasks...'
+        cd .build/SDG/CMake
+        ctest --verbose
   Linux:
     runs-on: ubuntu-18.04
     container: swift:5.1.3-bionic
