Began fetching Swift.

diff --git a/.github/workflows/Workspace Validation.yaml b/.github/workflows/Workspace Validation.yaml
--- a/.github/workflows/Workspace Validation.yaml
+++ b/.github/workflows/Workspace Validation.yaml
@@ -42,12 +42,24 @@ jobs:
     - name: Validate
       shell: bash
       run: |
+        repository_directory=$(pwd)
         cd '/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build'
         echo 'export -p > exported_environment.sh' > nested_bash.sh
         echo 'vcvarsall.bat x64 && "C:/Program Files/Git/usr/bin/bash" -c ./nested_bash.sh' > export_environment.bat
         cmd "/c export_environment.bat"
         source ./exported_environment.sh
-        if [ -z "$INCLUDE" ]; then echo "Failed to set up Visual Studio."; exit 1; fi
+        if [ -z "$INCLUDE" ]; then echo 'Failed to set up Visual Studio.'; exit 1; fi
+        cd "${repository_directory}"
+        mkdir -p '.build/SDG/Experimental Swift'
+        cd '.build/SDG/Experimental Swift'
+        curl -o swift-build.py 'https://raw.githubusercontent.com/compnerd/swift-build/master/utilities/swift-build.py'
+        python -m pip install --user azure-devops tabulate
+        echo 'Fetching Swift... (This is could to take up to 10 minutes.)'
+        python swift-build.py --build-id 'VS2019 Swift 5.2' --latest-artifacts --filter windows-x64 --download > /dev/null
+        7z x toolchain-windows-x64.zip
+        7z x sdk-windows-x64.zip
+        cd "${repository_directory}"
+        '.build/SDG/Experimental Swift/toolchain-windows-x64/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/bin/swift.exe' --version
         echo "Checkout succeeded."
   Linux:
     runs-on: ubuntu-18.04
